### PR TITLE
update codexlib

### PR DESCRIPTION
**Pull request by Truinto**
Fixed old CodexLib function (which searches in the wrong folder).
Also added a bit of automation. Cleanup should check for new commits and download new versions of CodexLib automatically.

DeployMod zips your mod folder after building in release mode. That way you cannot accidentally publish in debug. You will have to install 7zip, if you don't have already. There are other ways, but the filelist.txt feature is pretty nice. You can very easily change which files are getting shipped.
You can set the output folder with this line
``<zipoutput Include="$(TargetName)\$(TargetName).zip" />``

### CODE REVIEW

**Comment by Truinto** [comment]
~~Btw, I see you have ILRepack.Task. You also define a task. You need to explicitly tell it to not run the default task, otherwise it will automatically merge all output files (in addition to your own task).
You do that by creating a new file "ILRepack.targets" next to your csproj file. Leave it empty like below, so the automatic task doesn't do anything.~~
```xml
ILRepack.targets:
<?xml version="1.0" encoding="utf-8" ?>
<Project>
	<PropertyGroup>
	</PropertyGroup>
</Project>
```

Nevermind. This is only true for the package ILRepack.Lib.MSBuild.Task. But you have installed ILRepack.MSBuild.Task. I am not yet sure why this project exists twice.

**Comment by Truinto** [comment]
I can update this pull request, but i am not sure if you are still active. Or if you even like me to commit.

**Comment by Teraunce** [comment]
> I can update this pull request, but i am not sure if you are still active. Or if you even like me to commit.

Whoops. Welp, I updated the thing to work with the new beta (hopefully) without seeing this fork.

**Comment by Truinto** [comment]
Where can I see this code?

**Comment by Teraunce** [comment]
> Where can I see this code?

Either check my repositories or check this repositories' pull requests for the one I added.

**Comment by SpencerMycek** [comment]
Closing, but I do believe I have correctly made all these changes to the codebase.
It's just been long enough the conflicts might be causing issues now

**Pull request closed without merging**
